defaults: &defaults
  S3_BUCKET_NAME: gaiashop
  AWS_ACCESS_KEY_ID: AKIAJXP5OHEOPW7K4I4A
  AWS_SECRET_ACCESS_KEY: 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
  S3_REGION: ap-northeast-1
  SECRET_KEY_BASE: 6f7e6cf58c7cbd3d97d2f85b81573f6aeaf741bddc84206b404e7f0cb905194964a517fac8a82b12755a10bb5584d7b2d91861c4f136185dfbce3746fbbdd358
  GMAIL_USERNAME: usthtimetable@gmail.com
  GMAIL_PASSWORD: 1voi1la2

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults